# PostgreSQL. Versions 8.2 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: riverpix_development

test:
  <<: *default
  database: riverpix_test

production:
  <<: *default
  database: riverpix_production
  # username: riverpix
  # password: <%= ENV['RIVERPIX_DATABASE_PASSWORD'] %>